SET IDENTITY_INSERT Drugs ON;
TRUNCATE TABLE Drugs;

INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (1,'Prednisolone','PO',120,'mg','Day',2.5,'Tablets of 5, 10, 20 mg available. Liquid formulation of 5mg/ml available.','Prednisolone: given in three divided doses then two divided doses. Twice a day with meals.');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (2,'Vincristine','IV',2,'mg','Dose',0.1,'Slow intravenous push, 1mg/ml injection vials available.','ALERT: PLEASE ENSURE THAT VINCRISTINE IS ADMINISTERED ONLY AFTER COMPLETION OF INTRATHECAL METHOTREXATE INJECTION. THIS IS TO AVOID INADVERTENT INTRATHECAL INJECTION OF VINCRISTINE');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (3,'Methotrexate','IT',NULL,'mg','Dose',1,'ITMTX, Given by age<2 years= 8mg; 2-Less than 3 years= 10mg; ≥3 years= 12mg','mulation : Ampule 1ml =15mg ;Vial 3ml = 15mg. Children aged ≤ 3years do not receive cranial irradiation. Thus if the clinical conditions do not permit a lumbar puncture at this stage, this can be delayed.');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (4,'Pegaspargase','IM',NULL,'U','Dose',100,'Where available, the PEGylated preparation, Pegaspargase (Oncaspar®) will be administered','1000 units/m2( if surface area >0.6m2) given IM, not subcutaneously. 3,750 units per 5ml vial. DO NOT SHAKE. By intramuscular injection. No more than 2 mls in any one site. Do not use if solution is cloudy.');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (5,'E. coli L-asparaginase','IM',NULL,'U','Dose',500,'Where Pegaspargase is not available, native E. coli L-asparaginase will be administered','10,000units /m2. 10,000units & 5000 unit vials. Given intramuscular.No more than 2 ml at each site. Note: L-asparaginase dose may be rounded off to nearest vial dose; in such cases, a single dose should not be less than 6,000 units/sq.m');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (6,'Cotrimoxazole','PO',NULL,'mg','Day',10,'','');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (7,'Trimethoprim','PO',NULL,'mg','Day',NULL,'','');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (8,'Sulfamethoxazole','PO',NULL,'mg','Day',NULL,'','');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (9,'6-Mercaptopurine','PO',NULL,'mg','Day',0.5,'Medication to be taken in the evening without milk products. Administer on an empty stomach (at least 1 hour before the evening meal), no solids for 30 minutes after drug intake.','Formulation: 50 mg tablets. No suspension/liquid available. 60 mg/m2 (titratable) during maintenance. Doses to be taken once a day one hour after food in the evening. Do not administer with milk. The dose may be adjusted over days [ 1⁄2 and 1 tablet on alternate days as the tablet is small and not easy to divide]');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (10,'Dexamethasone','PO',20,'mg','Dose',0.5,'Tablets of 0.5, 2, 4 mg available. No liquid preparation.','Twice a day with meals.');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (11,'Methotrexate','PO',NULL,'mg','Dose',50,'Oral-MTX, Taken together with oral 6- Mercaptopurine. | rounded to the nearest 2.5mg','Formulation: 2.5 mg and 10 mg scored tablets. No suspension available. Is administered once a week, one hour after food. Omit dose in the week of IT Methotrexate.');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (12,'Cyclophosphamide','IV',NULL,'mg','Dose',50,'IV over 30minutes to 1 hour. Give Cyclophosphamide in 100mls in Saline over 30 minutes to 1 hour. Continue hydration at 125ml/m2 for 2-3 hours | Dilute Cyclophosphamide in up to 100ml and infuse over 30 minutes. Continue hydration at 125mL/m2 for 2 hours (no necessity for potassium in IV fluids)','Vials of 100, 200, 500mg& 1g. Administer in 100ml normal saline over 30 minutes; followed by fluids @ 125ml/m2 /hour for a period of 4 hours.');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (13,'Cytarabine','IV',NULL,'mg','Day',1,'(Ara-C), IV or SC push for 8 doses','Formulation Ready diluted vials, containing 100mg/ ml. Also available as a 20mg/ml (100mg/5ml) which is used for low dose boluses.');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (14,'Cytarabine','SC',NULL,'mg','Day',1,'(Ara-C), IV or SC push for 8 doses','');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (15,'Doxorubicin','IV',NULL,'mg','Dose',1,'IV infusion (1 hour) | IV infusion (4 – 6 hours)','Each vial 10mg/50mg base. Dilute to 2mg/ml. Infusion with 0.9% saline @ 25-45 mg/m2. Can further dilute with 0.9% saline for infusions by direct IV injection (slow bolus). [IV or SC in interim maintenance].Upto 3000mg/m2 IV [3hr infusion] every 12 hours');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (16,'Mitoxantrone','IV',NULL,'mg','Dose',1,'IV infusion over 1 hour, into a side-port of a free-flowing 0.9% Saline infusion | IV infusion over 15 minutes, into a side-port of a free-flowing 0.9% Saline infusion','');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (17,'Daunorubicin','IV',NULL,'mg','Dose',1,'IV infusion (1 hour) | IV infusion (1 hours). Given on the same days as Vincristine.','');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (18,'Methotrexate','IV',NULL,'mg','Dose',50,'All patients must be prehydrated as per guideline in Appendix. The initial 10% of dose is delivered over 30 minutes, the remaining 90% over 23 ½ hours. NB method and schedule of administration should be guided by Appendix 4. Timings of drug administration must be followed strictly.','');
INSERT INTO Drugs (id,drugName,route,maxDosage,unit,frequency,rounded ,description,footNote) VALUES (19,'Folinic acid','IV',NULL,'mg','Dose',NULL,'Further details of the folinic acid rescue are given in Appendix 4. Timings of drug administration must be followed strictly.','');

SET IDENTITY_INSERT Drugs OFF;
